name: Deploy Azure Function

on:
  push:
    paths:
      - 'qrCodeGenerator/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: |
        cd qrCodeGenerator
        dotnet restore

    - name: Build the function app
      run: |
        cd qrCodeGenerator
        dotnet publish -c Release -o publish

    - name: Zip the publish directory
      run: |
        cd qrCodeGenerator/publish
        zip -r ../publish.zip *

    - name: Authenticate to Azure
      id: auth
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Function App
      run: |
        az functionapp deployment source config-zip \
          --resource-group rg-qr-code-generator \
          --name maqrcg-func-app-001 \
          --src-path qrCodeGenerator/publish.zip
