name: Deploy Azure Function

on:
  push:
    paths:
      - 'qrCodeGenerator/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: |
        cd qrCodeGenerator
        dotnet restore

    - name: Build the function app
      run: |
        cd qrCodeGenerator
        dotnet publish -c Release -o publish

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ secrets.AZURE_FUNCTION_APP_NAME }}
        package: qrCodeGenerator/publish
        publish-profile: ${{ secrets.AZURE_FUNCTION_APP_PUBLISH_PROFILE }}
